In [1]:
!pip install torch torchvision

In [2]:
import torch
import numpy as np

In [3]:
torch.tensor(10)

tensor(10)

In [4]:
torch.tensor([10,20,30])

tensor([10, 20, 30])

In [5]:
scaler = torch.tensor(10)

In [6]:
type(scaler)

torch.Tensor

In [7]:
scaler

tensor(10)

In [8]:
scaler + 5

tensor(15)

In [9]:
scaler -10

tensor(0)

In [10]:
scaler * 3

tensor(30)

In [11]:
scaler / 5

tensor(2.)

In [14]:
scaler.dim() # kaç boyutlu olduğunu gösterir

0

In [15]:
scaler.shape

torch.Size([])

In [16]:
scaler.item()

10

In [17]:
type(scaler.item())

int

In [18]:
matrix = torch.tensor([[1,2],[3,4]])

In [19]:
matrix

tensor([[1, 2],
        [3, 4]])

In [20]:
matrix.dim()

2

In [21]:
matrix.shape

torch.Size([2, 2])

In [22]:
tensor_example = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [23]:
tensor_example

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [24]:
tensor_example.dim()

3

In [25]:
tensor_example.shape

torch.Size([1, 3, 3])

In [29]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = None,
                              device = None, #cpu, gpu
                              requires_grad = False # öğrenip öğrenemeyeceğini seçeriz
                              )

In [30]:
float_32_tensor.dtype

torch.float32