In [1]:
import torch
import numpy as np

In [2]:
random_array = np.random.randn(3,5)

In [3]:
random_array

array([[ 0.93247366,  1.78982162,  1.38023416, -0.39457951, -2.00728445],
       [ 0.2467022 , -0.15410013,  0.25695824, -0.86438781, -0.54206496],
       [ 0.35428292,  0.81754925, -0.50356539, -1.88463092,  0.22643447]])

In [4]:
type(random_array)

numpy.ndarray

In [5]:
random_array.shape

(3, 5)

In [6]:
random_array.ndim

2

In [7]:
random_matrix = torch.rand(size = (3,5))

In [8]:
random_matrix

tensor([[0.0103, 0.8929, 0.1960, 0.2187, 0.5922],
        [0.1263, 0.6912, 0.1153, 0.3270, 0.2281],
        [0.9807, 0.9629, 0.6285, 0.5205, 0.9719]])

In [9]:
type(random_matrix)

torch.Tensor

In [10]:
random_matrix.ndim

2

In [11]:
random_matrix.shape

torch.Size([3, 5])

In [12]:
random_matrix.dtype

torch.float32

In [13]:
random_image_tensor = torch.rand(size = (224,224,3))

In [14]:
random_image_tensor

tensor([[[0.3034, 0.9690, 0.5476],
         [0.8822, 0.8724, 0.3239],
         [0.9108, 0.2211, 0.4283],
         ...,
         [0.4844, 0.5627, 0.5219],
         [0.2041, 0.1155, 0.5657],
         [0.4858, 0.5586, 0.8702]],

        [[0.6469, 0.6037, 0.5356],
         [0.1577, 0.8360, 0.7825],
         [0.4631, 0.4557, 0.7119],
         ...,
         [0.4557, 0.7200, 0.2383],
         [0.9006, 0.7201, 0.4334],
         [0.5835, 0.9991, 0.3665]],

        [[0.6935, 0.3820, 0.4081],
         [0.7337, 0.0765, 0.9016],
         [0.4994, 0.8399, 0.9837],
         ...,
         [0.4188, 0.8775, 0.9234],
         [0.6354, 0.4748, 0.7599],
         [0.4321, 0.1954, 0.1200]],

        ...,

        [[0.4973, 0.8109, 0.3061],
         [0.8616, 0.6334, 0.9507],
         [0.7332, 0.2936, 0.9978],
         ...,
         [0.0378, 0.8859, 0.0285],
         [0.8390, 0.1030, 0.3950],
         [0.9264, 0.8190, 0.2279]],

        [[0.8808, 0.1937, 0.6671],
         [0.6422, 0.3133, 0.1375],
         [0.

In [16]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [18]:
random_image_tensor.dim()

3

In [19]:
zeros = torch.zeros(size = (3,2))

In [20]:
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [21]:
one = torch.ones(size = (3,2))

In [22]:
one

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [24]:
vector_with_arange = torch.arange(start=0,end=10,step=1)

In [25]:
vector_with_arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
vector_with_arange = torch.arange(start=0,end=10,step=2)

In [27]:
vector_with_arange

tensor([0, 2, 4, 6, 8])

In [28]:
similar_ones = torch.ones_like(input=vector_with_arange)

In [29]:
similar_ones

tensor([1, 1, 1, 1, 1])

In [30]:
X_tensor = torch.tensor([1,2,3])

In [31]:
X_tensor

tensor([1, 2, 3])

In [32]:
X_tensor +5

tensor([6, 7, 8])

In [33]:
X_tensor * 10

tensor([10, 20, 30])

In [34]:
X_tensor * np.pi

tensor([3.1416, 6.2832, 9.4248])

In [35]:
X_tensor.subtract(10)

tensor([-9, -8, -7])

In [36]:
X_tensor.add(10)

tensor([11, 12, 13])

In [37]:
X_tensor.divide(0.3)

tensor([ 3.3333,  6.6667, 10.0000])

In [38]:
X_tensor*X_tensor

tensor([1, 4, 9])

In [39]:
X_tensor - X_tensor

tensor([0, 0, 0])

In [40]:
X_tensor.add(X_tensor)

tensor([2, 4, 6])

In [41]:
y_tensor = torch.tensor([4,5])

In [42]:
y_tensor

tensor([4, 5])

In [43]:
X_tensor

tensor([1, 2, 3])