In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.tensor([1,2,3])

In [3]:
tensor*tensor

tensor([1, 4, 9])

In [4]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]]
)

In [5]:
matrix*matrix

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [7]:
matrix @ matrix # gerçek matrix çarpımı

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [9]:
torch.matmul(matrix,matrix) # torch ta matrix çarpımı

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [10]:
matrix.shape

torch.Size([3, 3])

In [11]:
tensor1 = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

In [12]:
tensor2 = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])

In [13]:
tensor1.shape

torch.Size([3, 2])

In [14]:
tensor2.shape

torch.Size([3, 2])

In [15]:
tensor1 @ tensor2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [17]:
tensor2.T # transpozesini alır

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [18]:
tensor2.T.shape

torch.Size([2, 3])

In [19]:
tensor1.shape

torch.Size([3, 2])

In [20]:
tensor1 @ tensor2.T

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [21]:
A = torch.tensor([[1,2,3]])

In [22]:
A.shape

torch.Size([1, 3])

In [23]:
A.ndim

2

In [24]:
B = torch.tensor([[4],[5],[6]])

In [25]:
B.shape

torch.Size([3, 1])

In [26]:
B.ndim

2

In [27]:
A @ B

tensor([[32]])

In [28]:
result = A @ B

In [29]:
result.shape

torch.Size([1, 1])

In [30]:
result.ndim

2