In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.arange(0,50,5)

In [3]:
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
tensor.min()

tensor(0)

In [6]:
tensor.max()

tensor(45)

In [7]:
tensor.sum()

tensor(225)

In [8]:
tensor.median()

tensor(20)

In [9]:
tensor.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [10]:
tensor.dtype

torch.int64

In [11]:
tensor = tensor.type(torch.float)

In [12]:
tensor

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [13]:
tensor.mean()

tensor(22.5000)

In [14]:
# argmax, argmin

In [15]:
tensor.max()

tensor(45.)

In [17]:
tensor.argmax() # indexlerin max değeri

tensor(9)

In [18]:
tensor[0]

tensor(0.)

In [19]:
tensor[1]

tensor(5.)

In [20]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [22]:
matrix.shape

torch.Size([2, 3])

In [23]:
matrix.ndim

2

In [24]:
matrix[0][0]

tensor(1)

In [25]:
# manipulationg tensor : reshaping, stacking, squeezing, unsqueezing

In [26]:
x = torch.arange(1,10,1)

In [27]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x.shape

torch.Size([9])

In [29]:
x.ndim

1

In [30]:
x_reshaped = x.reshape(1,9)

In [31]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [32]:
x_reshaped.shape

torch.Size([1, 9])

In [33]:
x_reshaped.ndim

2

In [35]:
y = torch.randn(224,224,3)

In [36]:
y

tensor([[[-1.7730,  0.1934,  1.3036],
         [ 2.0115,  0.9388, -0.7788],
         [ 0.3444, -1.1328,  0.3361],
         ...,
         [-0.0413,  1.0324,  0.7969],
         [ 0.2433, -0.7313, -0.4764],
         [ 1.4464, -0.0615,  0.4672]],

        [[ 0.4251, -1.3690, -0.9214],
         [-1.8298,  0.3593, -1.4441],
         [-2.1408, -0.7551, -1.0313],
         ...,
         [-0.0683, -0.7463, -0.3545],
         [-0.4183, -0.9183,  0.1798],
         [ 0.4190, -1.2606,  0.3580]],

        [[-0.2015, -0.0162,  0.0506],
         [ 0.7280,  1.0100,  1.1207],
         [-0.0424, -1.9110,  1.3750],
         ...,
         [-0.0440,  0.0453,  0.9476],
         [-0.7610,  0.0897, -2.5139],
         [-0.0091, -0.9041, -1.4182]],

        ...,

        [[ 0.1126, -0.9162, -0.9338],
         [ 1.7805, -0.0078,  1.0250],
         [-0.1077, -1.4357,  0.8883],
         ...,
         [-0.9461, -2.2084, -1.8715],
         [-0.6894,  2.2077,  0.5742],
         [-1.1712, -0.9003,  1.0400]],

        [[

In [37]:
y.shape

torch.Size([224, 224, 3])

In [38]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
x_reshaped = x.reshape(3,3)

In [42]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [43]:
x_reshaped = x.reshape(9,1)

In [44]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [45]:
# view

In [46]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [47]:
x_reshaped[0] = 20

In [48]:
x_reshaped

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [49]:
x

tensor([20,  2,  3,  4,  5,  6,  7,  8,  9])

In [50]:
x_view = x.view(9,1)

In [51]:
x_view

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [52]:
x_view[0]=10

In [53]:
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [54]:
x

tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [55]:
x_reshaped

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [56]:
# view -> contiguos tensor -> ramde bellekte art arda yazılan kısımdır

In [57]:
x = torch.tensor([[1,2,3],[4,5,5]])

In [58]:
x

tensor([[1, 2, 3],
        [4, 5, 5]])

In [60]:
x.is_contiguous() # arka arkaya saklanıp saklanmadığını kontrol eder

True

In [62]:
y = x.t()

In [63]:
y.is_contiguous()

False

In [64]:
y

tensor([[1, 4],
        [2, 5],
        [3, 5]])

In [65]:
x.is_contiguous()

True

In [66]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 5]])

In [69]:
y.view(1,6) # sadece arka arkaya  kısımlarda olur

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [68]:
y.reshape(1,6)

tensor([[1, 4, 2, 5, 3, 5]])

In [70]:
# stacking

In [71]:
x

tensor([[1, 2, 3],
        [4, 5, 5]])

In [72]:
torch.stack([x,x,x,x],dim=0)

tensor([[[1, 2, 3],
         [4, 5, 5]],

        [[1, 2, 3],
         [4, 5, 5]],

        [[1, 2, 3],
         [4, 5, 5]],

        [[1, 2, 3],
         [4, 5, 5]]])

In [75]:
torch.stack([x,x,x,x],dim=1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 5],
         [4, 5, 5],
         [4, 5, 5],
         [4, 5, 5]]])

In [76]:
# squeeze & unsqueeze

In [77]:
x

tensor([[1, 2, 3],
        [4, 5, 5]])

In [78]:
x.shape

torch.Size([2, 3])

In [80]:
x.ndim

2

In [82]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 5]])

In [83]:
x = torch.tensor([[1,2,3]])

In [84]:
x.ndim

2

In [85]:
x.shape

torch.Size([1, 3])

In [86]:
x.squeeze()

tensor([1, 2, 3])

In [87]:
x

tensor([[1, 2, 3]])

In [89]:
x.squeeze().ndim

1

In [90]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [91]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [92]:
x.unsqueeze(dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [93]:
y = x.unsqueeze(dim=0)

In [94]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [95]:
y.ndim

3

In [96]:
x.ndim

2

In [97]:
y.shape

torch.Size([1, 2, 3])

In [99]:
z = y.unsqueeze(dim=0)

In [100]:
z

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [101]:
z.shape

torch.Size([1, 1, 2, 3])

In [102]:
z.ndim

4

In [103]:
t = z.squeeze()

In [104]:
t.ndim

2

In [105]:
t.shape

torch.Size([2, 3])

In [106]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [109]:
x = torch.rand(size=(224,224,3))

In [110]:
x.shape

torch.Size([224, 224, 3])

In [112]:
x_permuted = x.permute(2,0,1) # axis 0-> 1, 1->2, 2->0 ( 1 birim sağa kaydırma)

In [113]:
x_permuted.shape

torch.Size([3, 224, 224])

In [114]:
# indexing & slicing

In [115]:
a = torch.arange(1,10,1)

In [116]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
a = a.reshape(1,3,3)

In [119]:
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [120]:
a[0][0][0]

tensor(1)

In [121]:
a.shape

torch.Size([1, 3, 3])

In [122]:
a.ndim

3

In [124]:
a[0][0][0]

tensor(1)

In [125]:
a[:,0,0]

tensor([1])

In [126]:
a[:,1,2]

tensor([6])

In [127]:
a[:,2,1]

tensor([8])

In [128]:
# : -> bütün değerleri al

In [129]:
a[:,:,2]

tensor([[3, 6, 9]])

In [130]:
a[:,1,:]

tensor([[4, 5, 6]])

In [131]:
# random seed

In [137]:
torch.manual_seed(42)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])