In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
device

'cuda'

In [5]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

In [6]:
device

'cuda'

In [7]:
tensor = torch.tensor([1,2,3])

In [8]:
tensor

tensor([1, 2, 3])

In [9]:
tensor.device

device(type='cpu')

In [10]:
# manuel

In [11]:
tensor_on_gpu = tensor.to(device)

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [13]:
tensor.numpy()

array([1, 2, 3])

In [14]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [15]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [16]:
# context manager

In [17]:
with torch.device(device):
    tensor2 = torch.tensor([1,2,3])
    layer = torch.nn.Linear(20,30)

In [18]:
tensor2.device

device(type='cuda', index=0)

In [19]:
layer.weight.device

device(type='cuda', index=0)

In [20]:
tensor3 = torch.tensor([4,5,6])

In [21]:
tensor3.device

device(type='cpu')

In [22]:
# torch.set_default_device

In [23]:
device

'cuda'

In [24]:
torch.set_default_device(device)

In [25]:
tensor4 = torch.tensor([1,2,3])
layer2 = torch.nn.Linear(10,20)

In [26]:
tensor4.device

device(type='cuda', index=0)

In [28]:
layer2.weight.device

device(type='cuda', index=0)

In [29]:
tensor3.device

device(type='cpu')

In [30]:
import os

print(os.getcwd())

C:\Users\rarsl\deeplearning
